services:
  web:
    build: .
    container_name: django_app
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=codeleap.settings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=codeleap
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: codeleap
    ports:
      - "5432:5432"

  migrate:
    build: .
    container_name: django_migrate
    command: poetry run python manage.py migrate
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=codeleap
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
